export const ADD_TO_CART = 'ADD_TO_CART'
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
